### ISSUE TITLE
Error: "Evaluation error: No tidyselect variables were registered", when "assess_prediction" function is used

### ISSUE THREAD

**Issue by MohamedRefaat92** [topepo/user2018#1]
Hi,
I am facing a problem running the "assess_prediction" function from slide 41. It gives the following error when I map it to the **cv_splits** object

```
Error in mutate_impl(.data, dots) : 
  Evaluation error: No tidyselect variables were registered
Call `rlang::last_error()` to see a backtrace.
In addition: Warning message:
Please use `new_data` instead of `newdata` with `bake`. 
In recipes versions >= 0.1.4, this will cause an error.  
```
When I made a slight modification to the function by removing `everything() ` argument from `bake()` as shown below
```
assess_predictions <- function(split_obj, rec_obj, mod_obj) {
  raw_data <- assessment(split_obj)
  proc_x <- bake(rec_obj, newdata = raw_data, all_predictors())
  # Now save _all_ of the columns and add predictions. 
  bake(rec_obj, newdata = raw_data) %>%
    mutate(
      .fitted = predict(mod_obj, newdata = proc_x),
      .resid = Sale_Price - .fitted,  # Sale_Price is already logged by the recipe
      # Save the original row number of the data
      .row = as.integer(split_obj, data = "assessment")
    )
}
```
the function worked fine! 

Would you please help me interpret the error and why it only worked after removing `everything() `?

Thanks

**Comment by topepo** [comment]
The `recipes` package was [updated](https://cran.r-project.org/web/packages/recipes/news/news.html) with some [breaking changes](https://www.tidyverse.org/articles/2018/11/tidymodels-update-nov-18/). The error pretty much explains it:

> Please use `new_data` instead of `newdata` with `bake`.

**Comment by MohamedRefaat92** [comment]
First of all, thanks for your prompt response. 
I thought this was just a warning that I can neglect.

Now  after replacing `new_data` with `newdata`, I get this new error
```
 Error in mutate_impl(.data, dots) : 
  Evaluation error: Column `.fitted` must be length 222 (the number of rows) or one, not 1977.
```
I understand that 222 is the number of rows of the assessment group and 1977 is of the analysis group, but I don't know how to solve this error.

**Comment by MohamedRefaat92** [comment]
I would like it to add that the error above regarding the row numbers is also resolved only after removing `everything()` from `bake()`. So the function now looks as follows
```
assess_predictions <- function(split_obj, rec_obj, mod_obj) {
  raw_data <- assessment(split_obj)
  proc_x <- bake(rec_obj, newdata = raw_data, all_predictors())
  # Now save _all_ of the columns and add predictions. 
  bake(rec_obj, newdata = raw_data,e̶v̶e̶r̶y̶t̶h̶i̶n̶g̶(̶)̶) %>%
    mutate(
      .fitted = predict(mod_obj, newdata = proc_x),
      .resid = Sale_Price - .fitted,  # Sale_Price is already logged by the recipe
      # Save the original row number of the data
      .row = as.integer(split_obj, data = "assessment")
    )
}

```
But I still don't know why does this happen !

**Comment by MohamedRefaat92** [comment]
I think I got it resolved. The stupid mistake I made and caused the error above is that I used `new_data() `instead of `newdata()` with, not only with `bake()`, but also with `fitted()`.
